runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

# This sample incurs costs to run on the App Engine flexible environment.
# See https://cloud.google.com/appengine/pricing for details.

handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto



service_account: secure-sorter-429017-e2@appspot.gserviceaccount.com


env_variables:
  DJANGO_SETTINGS_MODULE: "calmjenn.settings"
  # Add any other environment variables you need, for example:
  # SECRET_KEY: "your-secret-key"
  # DATABASE_URL: "your-database-url"
